name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s app/tests -p 'test_*.py'
        
      - name: Deploy to Vultr server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PATH: /var/www/defect-tracking-application/
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          rsync -avz -e "ssh -i ssh_key -p $SSH_PORT" --exclude 'env' --exclude '__pycache__' . $SSH_USER@$SSH_HOST:$DEPLOY_PATH
          ssh -i ssh_key -p $SSH_PORT $SSH_USER@$SSH_HOST << EOF
            cd $DEPLOY_PATH
            source env/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flask
          EOF
          rm ssh_key
